x-kafka-env: &kafka-env
  KAFKA_PROCESS_ROLES: broker,controller
  KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka-1:9093,1@kafka-2:9093,2@kafka-3:9093
  KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:19092,CONTROLLER://:9093
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
  KAFKA_CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
  KAFKA_LOG_DIRS: /var/lib/kafka/data

x-kafka-common: &kafka-common
  image: apache/kafka:3.9.0
  healthcheck:
    test: ["CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1"]
    interval: 5s
    timeout: 10s
    retries: 10

services:
  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - "19092:19092"
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 0
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092
    networks:
      - kafka-net
    volumes:
      - kafka-1-data:/var/lib/kafka/data

  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - "19094:19092"
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:19094
    networks:
      - kafka-net
    volumes:
      - kafka-2-data:/var/lib/kafka/data

  kafka-3:
    <<: *kafka-common
    container_name: kafka-3
    ports:
      - "19096:19092"
    environment:
      <<: *kafka-env
      KAFKA_NODE_ID: 2
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://localhost:19096
    networks:
      - kafka-net
    volumes:
      - kafka-3-data:/var/lib/kafka/data

  k6:
    image: mostafamoradian/xk6-kafka:1.2.0
    container_name: k6-load-test
    volumes:
      - ./k6:/scripts
    command: run /scripts/script.js
    networks:
      - kafka-net
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      kafka-3:
        condition: service_healthy

volumes:
  kafka-1-data:
  kafka-2-data:
  kafka-3-data:

networks:
  kafka-net: