[project]
name = "airflow_example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.9",
]
