[package]
name = "datafusion_example"
version = "0.1.0"
edition = "2024"

[dependencies]
datafusion = "50.3.0"
futures = "0.3.31"
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.17"
async-stream = "0.3"
chrono = { version = "0.4", features = ["clock"] }
